name: code-quality

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out the repository 
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Analysing the code with black
      run: python -m black src --check --diff
    
    - name: Analysing the code with isort
      run: python -m isort src --diff --check-only --profile black
    
    - name: Analysing the code with pylint 
      run: python -m pylint src
